"""Add emote

Revision ID: eb75eb056dc0
Revises: c43fa190d9fb
Create Date: 2026-01-08 14:11:10.303205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb75eb056dc0'
down_revision: Union[str, Sequence[str], None] = 'c43fa190d9fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(), nullable=True),
    sa.Column('source', sa.Enum('SEVENTV', name='emotesource'), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('emote_pkey'))
    )
    op.add_column('sticker', sa.Column('external_id', sa.String(), nullable=True))
    op.add_column('sticker', sa.Column('emote_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(op.f('sticker_external_id_key'), 'sticker', ['external_id'])
    op.create_foreign_key(op.f('sticker_emote_id_fkey'), 'sticker', 'emote', ['emote_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sticker_emote_id_fkey'), 'sticker', type_='foreignkey')
    op.drop_constraint(op.f('sticker_external_id_key'), 'sticker', type_='unique')
    op.drop_column('sticker', 'emote_id')
    op.drop_column('sticker', 'external_id')
    op.drop_table('emote')
    op.execute('drop type emotesource;')
    # ### end Alembic commands ###
