"""Make file_id in Emote required

Revision ID: ace62b9d1549
Revises: c4f0154c94bb
Create Date: 2026-01-21 12:58:45.019866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ace62b9d1549'
down_revision: Union[str, Sequence[str], None] = 'c4f0154c94bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("update emote set file_id = 'BQACAgIAAxUHaW96e-g3dml5viZ9t8bcwry183AAAgaSAAKZkXhLWvcl27qINVc4BA' where file_id is null;")
    op.alter_column('emote', 'file_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('emote', 'file_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
