"""Initial

Revision ID: c43fa190d9fb
Revises: 
Create Date: 2026-01-06 13:36:28.860275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c43fa190d9fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('telegram_id', name=op.f('user_telegram_id_key'))
    )
    op.create_table('sticker_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('REGULAR', 'CUSTOM_EMOJI', name='stickertype'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('sticker_set_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sticker_set_pkey')),
    sa.UniqueConstraint('name', name=op.f('sticker_set_name_key'))
    )
    op.create_table('sticker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('REGULAR', 'CUSTOM_EMOJI', name='stickertype'), nullable=False),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('sticker_set_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sticker_set_id'], ['sticker_set.id'], name=op.f('sticker_sticker_set_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sticker_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sticker')
    op.drop_table('sticker_set')
    op.drop_table('user')
    op.execute('drop type stickertype;')
    # ### end Alembic commands ###
