"""add new emote fields and more

Revision ID: c4f0154c94bb
Revises: eb75eb056dc0
Create Date: 2026-01-10 12:47:37.363997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4f0154c94bb'
down_revision: Union[str, Sequence[str], None] = 'eb75eb056dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emote', 'emoji')
    op.add_column('emote', sa.Column('file_url', sa.String(), nullable=False, server_default='forsen'))
    op.execute("create type emoteformat as enum ('STATIC', 'VIDEO');")
    op.add_column('emote', sa.Column('format', sa.Enum('STATIC', 'VIDEO', name='emoteformat'), nullable=False, server_default='STATIC'))
    op.add_column('emote', sa.Column('name', sa.String(), nullable=False, server_default='forsen'))
    op.alter_column('emote', 'file_url', server_default=None)
    op.alter_column('emote', 'format', server_default=None)
    op.alter_column('emote', 'name', server_default=None)
    op.drop_constraint(op.f('sticker_external_id_key'), 'sticker', type_='unique')
    op.alter_column('sticker', 'external_id', new_column_name='file_unique_id')
    op.create_unique_constraint(op.f('sticker_file_unique_id_key'), 'sticker', ['file_unique_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sticker_file_unique_id_key'), 'sticker', type_='unique')
    op.alter_column('sticker', 'file_unique_id', new_column_name='external_id')
    op.create_unique_constraint(op.f('sticker_external_id_key'), 'sticker', ['external_id'], postgresql_nulls_not_distinct=False)
    op.add_column('emote', sa.Column('emoji', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('emote', 'format')
    op.drop_column('emote', 'file_url')
    op.drop_column('emote', 'name')
    op.execute('drop type emoteformat;')
    # ### end Alembic commands ###
